// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:proj/models/workout.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SetAdapter());
    registerAdapter(WorkoutAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SetAdapter());
    registerAdapter(WorkoutAdapter());
  }
}
